<?php

declare(strict_types=1);

namespace App\Tests\Property;

use App\Service\JwtService;
use Eris\Generator;
use Eris\TestTrait;
use PHPUnit\Framework\TestCase;

/**
 * Property-based tests for JwtService.
 *
 * Feature: yii2-to-yii3-migration, Property 6: JWT HS256 签名不变量
 *
 * **Validates: Requirements 3.6**
 *
 * Property 6: For any token generated by JwtService, the parsed token's signing
 * algorithm should be HS256, and the token should pass validation within its TTL.
 */
final class JwtPropertyTest extends TestCase
{
    use TestTrait;

    private string $keyFilePath;
    private JwtService $jwtService;

    protected function setUp(): void
    {
        $this->keyFilePath = tempnam(sys_get_temp_dir(), 'jwt_prop_key_');
        file_put_contents($this->keyFilePath, bin2hex(random_bytes(32)));

        $this->jwtService = new JwtService($this->keyFilePath);
    }

    protected function tearDown(): void
    {
        if (file_exists($this->keyFilePath)) {
            unlink($this->keyFilePath);
        }
    }

    /**
     * Property 6: JWT HS256 签名不变量
     *
     * For any positive user ID, a token generated by JwtService:
     * 1. Uses HS256 signing algorithm
     * 2. Passes validation (validateToken returns true)
     * 3. Round-trips through parseToken returning the same user_id
     *
     * **Validates: Requirements 3.6**
     *
     * @eris-repeat 100
     */
    public function testJwtHs256SigningInvariant(): void
    {
        $this->forAll(
            Generator\choose(1, 999999999)
        )
            ->then(function (int $userId): void {
                $token = $this->jwtService->generateToken($userId);

                // Token must be valid JWT format (3 dot-separated parts)
                $parts = explode('.', $token);
                $this->assertCount(3, $parts, 'JWT must have 3 dot-separated parts');

                // Header must specify HS256 algorithm
                $header = json_decode(
                    base64_decode(strtr($parts[0], '-_', '+/'), true),
                    true,
                );
                $this->assertSame('HS256', $header['alg'], 'JWT must use HS256 algorithm');

                // Token must pass validation within its TTL
                $this->assertTrue(
                    $this->jwtService->validateToken($token),
                    "Token for userId {$userId} must be valid",
                );

                // parseToken must return the same user_id
                $parsed = $this->jwtService->parseToken($token);
                $this->assertNotNull($parsed, "parseToken must succeed for userId {$userId}");
                $this->assertSame(
                    $userId,
                    $parsed['user_id'],
                    "Parsed user_id must match original for userId {$userId}",
                );
            });
    }
}
